spring:
  application:
    name: helloWebflux
  r2dbc:
    url: r2dbc:mysql://localhost:3306/testdb
    username: tester
    password: tester1234
  data:
    redis:
      host: localhost
      port: 6380
logging:
  level:
    root: INFO

server:
  port: 8080
